<?php
/**
 * system Autoload component; auto-generated by system generator
 * 
 * @author mithun mohan
 * @copyright Mofilm (c) 2009-2010
 * @package scorpio
 * @subpackage system
 * @category systemAutoload
 */
return array(
	'momusicArtist' => 'momusic/artist.class.php',
	'momusicWorks' => 'momusic/works.class.php',
	'momusicTags' => 'momusic/tags.class.php',
	'momusicTag' => 'momusic/tag.class.php',
	'momusicWorkSearch' => 'momusic/work/search.class.php',
	'momusicWorkSearchResult' => 'momusic/work/search/result.class.php',
	'momusicSyncMovies' => 'momusic/sync/movies.class.php',
	'momusicMash' => 'momusic/mash.class.php',
	'momusicUtilities' => 'momusic/utilities.class.php',
	'baseSolrSearch' => 'momusic/search.class.php',
	'momusicKeywordSearch' => 'momusic/keyword/search.class.php',
	'momusicSearchResult'  => 'momusic/result.class.php',
	'momusicResultSet'  => 'momusic/search/result.class.php',
	'momusicException'  => 'momusic/exception.class.php',
	'momusicType'  => 'momusic/type.class.php',
	'momusicTypeLeaf'  => 'momusic/type/leaf.class.php',
	'momusicMusic'  => 'momusic/music.class.php',
	'momusicSources'  => 'momusic/sources.class.php',
	'momusicWork' => 'momusic/work.class.php',
	'momusicReportDetails' => 'momusic/report/details.class.php',
        'momusicFeaturedArtist' => 'momusic/featured/artist.class.php',
        'momusicCoverimage' => 'momusic/coverimage.class.php',
        'momusicHandpickedmusic' => 'momusic/handpickedmusic.class.php'
    
	
);