<?php
/**
 * system Autoload component; auto-generated by system generator
 * 
 * @author Dave Redfern
 * @copyright Mofilm (c) 2009-2010
 * @package scorpio
 * @subpackage system
 * @category systemAutoload
 */
return array(
	'reportCentreException' => 'reportCentre/exception.class.php',
	'reportCentreGenerator' => 'reportCentre/generator.class.php',
	'reportCentreReportDeliveryType' => 'reportCentre/report/delivery/type.class.php',
	'reportCentreReportQueue' => 'reportCentre/report/queue.class.php',
	'reportCentreReportSchedule' => 'reportCentre/report/schedule.class.php',
	'reportCentreReportScheduleType' => 'reportCentre/report/schedule/type.class.php',
	'reportCentreReportSet' => 'reportCentre/report/set.class.php',
	'reportCentreReportStatus' => 'reportCentre/report/status.class.php',
	'reportCentreReportType' => 'reportCentre/report/type.class.php',
	'reportCentreReport' => 'reportCentre/report.class.php',
);