<?php
/**
 * system Autoload component; auto-generated by system generator
 * 
 * @author Dave Redfern
 * @copyright Dave Redfern (c) 2007-2010
 * @package scorpio
 * @subpackage system
 * @category systemAutoload
 */
return array(
	'dbManager'										=> 'db/manager.class.php',
	'dbBackup'										=> 'db/backup.class.php',
	'dbOptions'										=> 'db/options.class.php',
	'dbUtilities'									=> 'db/utilities.class.php',
	'dbMapper'										=> 'db/mapper/mapper.class.php',
	'dbMapperPhpTypes'								=> 'db/mapper/phpTypes.class.php',
	'dbMapperTableDefinition'						=> 'db/mapper/definitions/table.class.php',
	'dbMapperFieldDefinition'						=> 'db/mapper/definitions/field.class.php',
	'dbMapperIndexDefinition'						=> 'db/mapper/definitions/index.class.php',
	'dbMapperConstraintDefinition'					=> 'db/mapper/definitions/constraint.class.php',
	'dbMapperFieldSet'								=> 'db/mapper/sets/field.class.php',
	'dbMapperIndexSet'								=> 'db/mapper/sets/index.class.php',
	'dbMapperTableSet'								=> 'db/mapper/sets/table.class.php',
	'dbMapperConstraintSet'							=> 'db/mapper/sets/constraint.class.php',

	'dbDriver'										=> 'db/driver.class.php',
	'dbDriverMySql'									=> 'db/driver/mysql/driver.class.php',
	'dbDriverMySqlBackup'							=> 'db/driver/mysql/backup.class.php',
	'dbDriverMySqlUtilities'						=> 'db/driver/mysql/utilities.class.php',
	'dbDriverMySqlTypes'							=> 'db/driver/mysql/types.class.php',
	'dbDriverPgSql'									=> 'db/driver/pgsql/driver.class.php',
	'dbDriverPgSqlUtilities'						=> 'db/driver/pgsql/utilities.class.php',
	'dbDriverPgSqlTypes'							=> 'db/driver/pgsql/types.class.php',
	'dbDriverSqlite'								=> 'db/driver/sqlite/driver.class.php',
	'dbDriverSqliteUtilities'						=> 'db/driver/sqlite/utilities.class.php',
	'dbDriverSqliteTypes'							=> 'db/driver/sqlite/types.class.php',
	
	'dbUpdateCommandStatus'							=> 'db/update/command/status.class.php',
	'dbUpdateCommandUpdate'							=> 'db/update/command/update.class.php',
	'dbUpdateCommandBackup'							=> 'db/update/command/backup.class.php',
	'dbUpdateManager'								=> 'db/update/manager.class.php',
	'dbUpdateLog'									=> 'db/update/log.class.php',
	'dbUpdateDefinition'							=> 'db/update/definition.class.php',
	'dbUpdateReport'								=> 'db/update/report.class.php',
	'dbUpdateReportSet'								=> 'db/update/reportSet.class.php',

	'dbException'									=> 'db/exception.class.php',
	'dbManagerCannotBeInstantiated'					=> 'db/exception.class.php',
	'dbManagerMissingDsn'							=> 'db/exception.class.php',
	'dbManagerDsnToDbOptionsParseFailed'			=> 'db/exception.class.php',
	'dbManagerInvalidDriver'						=> 'db/exception.class.php',
	
	'dbDriverException'								=> 'db/exception.class.php',
	'dbDriverTransactionException'					=> 'db/exception.class.php',
	'dbDriverMissingDbOption'						=> 'db/exception.class.php',
	
	'dbOptionsException'							=> 'db/exception.class.php',
	
	'dbUtilitiesException'							=> 'db/exception.class.php',
	
	'dbMapperException'								=> 'db/exception.class.php',
	'dbMapperNoDatabaseSelected'					=> 'db/exception.class.php',
);