<?php
/**
 * system Autoload component; auto-generated by system generator
 * 
 * @author Dave Redfern
 * @copyright Dave Redfern (c) 2007-2010
 * @package scorpio
 * @subpackage system
 * @category systemAutoload
 */
return array(
	'mvcAutoload' => 'mvc/autoload.class.php',
	'mvcAutoloadException' => 'mvc/exception.class.php',
	'mvcAutoloadClassCouldNotBeLoaded' => 'mvc/exception.class.php',
	
	'mvcRequest' => 'mvc/request.class.php',
	'mvcResponse' => 'mvc/response.class.php',
	'mvcException' => 'mvc/exception.class.php',
	'mvcSessionBase' => 'mvc/session/base.class.php',

	'mvcCaptchaController' => 'mvc/captcha/controller.class.php',
	'mvcCaptchaModel' => 'mvc/captcha/model.class.php',
	
	'mvcControllerAction' => 'mvc/controller/action.class.php',
	'mvcControllerActions' => 'mvc/controller/actions.class.php',
	'mvcControllerBase' => 'mvc/controller/base.class.php',
	'mvcControllerException' => 'mvc/controller/exception.class.php',
	'mvcControllerMapper' => 'mvc/controller/mapper.class.php',
	'mvcControllerMap' => 'mvc/controller/map.class.php',
	'mvcControllerMapPath' => 'mvc/controller/mapPath.class.php',
	'mvcControllerMenuItem' => 'mvc/controller/menuItem.class.php',
	'mvcControllerMenuItems' => 'mvc/controller/menuItems.class.php',
	'mvcControllerViews' => 'mvc/controller/views.class.php',
	
	'mvcDistributor' => 'mvc/distributor.class.php',
	'mvcDistributorBase' => 'mvc/distributor/base.class.php',
	'mvcDistributorException' => 'mvc/distributor/exception.class.php',
	'mvcDistributorOfflineException' => 'mvc/distributor/exception.class.php',
	'mvcDistributorDatabaseOfflineException' => 'mvc/distributor/exception.class.php',
	'mvcDistributorInvalidRequestException' => 'mvc/distributor/exception.class.php',
	'mvcDistributorInvalidActionException' => 'mvc/distributor/exception.class.php',
	'mvcDistributorPlugin' => 'mvc/distributor/plugin.class.php',
	'mvcDistributorPluginAuditLog' => 'mvc/distributor/plugin/auditLog.class.php',
	'mvcDistributorPluginDetectDevice' => 'mvc/distributor/plugin/detectDevice.class.php',
	'mvcDistributorPluginDispatchTimer' => 'mvc/distributor/plugin/dispatchTimer.class.php',
	'mvcDistributorPluginErrorHandler' => 'mvc/distributor/plugin/errorHandler.class.php',
	'mvcDistributorPluginLocale' => 'mvc/distributor/plugin/locale.class.php',
	'mvcDistributorPluginLog' => 'mvc/distributor/plugin/log.class.php',
	'mvcDistributorPluginMemTracker' => 'mvc/distributor/plugin/memTracker.class.php',
	'mvcDistributorPluginSession' => 'mvc/distributor/plugin/session.class.php',
	'mvcDistributorPluginSet' => 'mvc/distributor/plugin/set.class.php',
	'mvcDistributorPluginTranslate' => 'mvc/distributor/plugin/translate.class.php',

	'mvcErrorController' => 'mvc/error/controller.class.php',
	'mvcErrorInterface' => 'mvc/error/interface.iface.php',
	'mvcErrorView' => 'mvc/error/view.class.php',
	
	'mvcFileUpload' => 'mvc/file/upload.class.php',
	'mvcFileObject' => 'mvc/file/object.class.php',
	'mvcFileSet' => 'mvc/file/set.class.php',
	'mvcFileException' => 'mvc/file/exception.class.php',
	'mvcFileUploadException' => 'mvc/file/exception.class.php',
	'mvcFileUploadInvalidException' => 'mvc/file/exception.class.php',
	'mvcFileUploadMoveUploadedFileException' => 'mvc/file/exception.class.php',
	'mvcFileUploadNoFileUploadedException' => 'mvc/file/exception.class.php',
	'mvcFileUploadArrayException' => 'mvc/file/exception.class.php',
	'mvcFileFileStoreDoesNotExistException' => 'mvc/file/exception.class.php',
	'mvcFileFileStoreNotReadableException' => 'mvc/file/exception.class.php',
	'mvcFileFileStoreNotWritableException' => 'mvc/file/exception.class.php',
	'mvcFileFileStoreBuildFailedException' => 'mvc/file/exception.class.php',
	'mvcFileFileStoreBuildSubFoldersFailedException' => 'mvc/file/exception.class.php',
	
	'mvcImageController' => 'mvc/image/controller.class.php',
	'mvcImageModel' => 'mvc/image/model.class.php',
	'mvcImageProcessor' => 'mvc/image/processor.iface.php',
	
	'mvcMapException' => 'mvc/controller/exception.class.php',
	'mvcMapConfigFileDoesNotExist' => 'mvc/controller/exception.class.php',
	'mvcMapConfigFileNotReadable' => 'mvc/controller/exception.class.php',
	'mvcMapConfigFileIsNotValidXml' => 'mvc/controller/exception.class.php',
	'mvcMapConfigFileIsNotWritable' => 'mvc/controller/exception.class.php',
	'mvcMapConfigFileCouldNotBeWritten' => 'mvc/controller/exception.class.php',
	'mvcMapConfigurationDataNotLoaded' => 'mvc/controller/exception.class.php',
	'mvcMapControllerNotFound' => 'mvc/controller/exception.class.php',
	'mvcMapNonUniqueControllerName' => 'mvc/controller/exception.class.php',
	'mvcMapNoPathComponentsToSearch' => 'mvc/controller/exception.class.php',
	
	'mvcModelBase' => 'mvc/model/base.class.php',
	'mvcModelException' => 'mvc/model/exception.class.php',
	
	'mvcSiteBuilder' => 'mvc/site/builder.class.php',
	'mvcSiteConfig' => 'mvc/site/config.class.php',
	'mvcSiteConfigException' => 'mvc/site/exception.class.php',
	'mvcSiteConfigNoControllerMapDefined' => 'mvc/site/exception.class.php',
	'mvcSiteException' => 'mvc/site/exception.class.php',
	'mvcSiteTools' => 'mvc/site/tools.class.php',
	'mvcSiteToolsException' => 'mvc/site/exception.class.php',

	'mvcStaticController' => 'mvc/static/controller.class.php',
	'mvcStaticModel' => 'mvc/static/model.class.php',
	'mvcStaticView' => 'mvc/static/view.class.php',
	
	'mvcViewBase' => 'mvc/view/base.class.php',
	'mvcViewEngineBase' => 'mvc/view/engine/base.class.php',
	'mvcViewEngineFactory' => 'mvc/view/engine/factory.class.php',
	'mvcViewEngineGeneric' => 'mvc/view/engine/generic.class.php',
	'mvcViewEnginePhp' => 'mvc/view/engine/php.class.php',
	'mvcViewEnginePhptal' => 'mvc/view/engine/phptal.class.php',
	'mvcViewEngineSavant3' => 'mvc/view/engine/savant3.class.php',
	'mvcViewEngineSmarty' => 'mvc/view/engine/smarty.class.php',
	'mvcViewEngineTwig' => 'mvc/view/engine/twig.class.php',
	'mvcViewException' => 'mvc/view/exception.class.php',
	'mvcViewInvalidTemplateException' => 'mvc/view/exception.class.php',
	'mvcViewGeneric' => 'mvc/view/generic.class.php',
	'mvcViewHelper' => 'mvc/view/helper.class.php',
	'mvcViewHelperInterface' => 'mvc/view/helper/interface.iface.php',
	'mvcViewHelperFactory' => 'mvc/view/helper/factory.class.php',
	'mvcViewMeta' => 'mvc/view/meta.class.php',
	'mvcViewResource' => 'mvc/view/resource.class.php',
	'mvcViewCss' => 'mvc/view/css.class.php',
	'mvcViewJavascript' => 'mvc/view/javascript.class.php',
);