<?php
/**
 * system Autoload component; auto-generated by system generator
 * 
 * @author Dave Redfern
 * @copyright Dave Redfern (c) 2007-2010
 * @package scorpio
 * @subpackage system
 * @category systemAutoload
 */
return array(
	'PHPMailer'	=> 'phpMailer/class.phpmailer.php',
	'SMTP'		=> 'phpMailer/class.smtp.php',
	'POP3'		=> 'phpMailer/class.pop3.php',
);
