<?php
/**
 * system Autoload component; auto-generated by system generator
 * 
 * @author Dave Redfern
 * @copyright Dave Redfern (c) 2007-2010
 * @package scorpio
 * @subpackage system
 * @category systemAutoload
 */
return array(
	'testCaseScorpio' => 'test/caseScorpio.class.php',
	'testCommand' => 'test/command.class.php',
	'testCommandListTestCases' => 'test/listTestCases.class.php',
	'testSuiteHtmlReporter' => 'test/suiteHtmlReporter.class.php',
	'testSuitePackage' => 'test/suitePackage.class.php',
	'testSuitePackages' => 'test/suitePackages.class.php',
	'testSuiteTools' => 'test/suiteTools.class.php',
);