<?php
/**
 * system Autoload component; auto-generated by system generator
 * 
 * @author Dave Redfern
 * @copyright Dave Redfern (c) 2007-2010
 * @package scorpio
 * @subpackage system
 * @category systemAutoload
 */
return array(
	'wurflException' => 'wurfl/exception.class.php',
	'wurflCapability' => 'wurfl/capability.class.php',
	'wurflCapabilityGroup' => 'wurfl/capabilityGroup.class.php',

	'wurflCommandCapabilityParser' => 'wurfl/command/capabilityParser.class.php',
	'wurflCommandDownload' => 'wurfl/command/download.class.php',
	'wurflCommandParser' => 'wurfl/command/parser.class.php',
	'wurflCommandRebuild' => 'wurfl/command/rebuild.class.php',
	'wurflCommandTest' => 'wurfl/command/test.class.php',

	'wurflDeviceCache' => 'wurfl/device/cache.class.php',
	'wurflDeviceCapability' => 'wurfl/device/capability.class.php',
	'wurflDeviceCapabilities' => 'wurfl/device/capabilities.class.php',
	'wurflDevice' => 'wurfl/device.class.php',
	'wurflExport' => 'wurfl/export.class.php',
	'wurflManager' => 'wurfl/manager.class.php',
	'wurflManufacturer' => 'wurfl/manufacturer.class.php',
	'wurflSearch' => 'wurfl/search.class.php',
	'wurflResultSet' => 'wurfl/resultSet.class.php',
	'wurflParser' => 'wurfl/parser.class.php',
);