<?php
/**
 * testSuite.php
 * 
 * Provides the framework for running tests generated by "Generator" component. Tests
 * should be packaged in a directory within "tests". The filename should be testCLASSNAME
 * in CamelCaps.
 * 
 * All tests must extend the base test class.
 * 
 * Test files can contain any amount of testing: so long as it is valid for SimpleTest.
 * 
 * @author Dave Redfern
 * @copyright Dave Redfern (c) 2007-2010
 * @package scorpio
 * @subpackage tools
 * @category testSuite
 * @version $Rev: 9 $
 */

/*
 * Load dependencies
 */
require_once(dirname(dirname(__FILE__)).DIRECTORY_SEPARATOR.'libraries'.DIRECTORY_SEPARATOR.'system.inc');

/**
 * testSuite
 * 
 * Provides the framework for running tests generated by "Generator" component. Tests
 * should be packaged in a directory within "tests". The filename should be testCLASSNAME
 * in CamelCaps.
 * 
 * All tests must extend the base test class.
 * 
 * Test files can contain any amount of testing: so long as it is valid for SimpleTest.
 *
 * @package scorpio
 * @subpackage tools
 * @category testSuite
 */
$oApp = new cliApplication(
	'Test Suite',
	'Runs tests on the command line to verify that objects are working correctly. '.
	'Can be used in conjunction with Generator to automate class building and '.
	'testing. All tests should be stored as a package e.g. a single folder '.
	'containing all tests for that group.'
);
$oRequest = cliRequest::getInstance()->setApplication($oApp);
$oApp->getCommandChain()
	->addCommand(new cliCommandLog($oRequest))
	->addCommand(new cliCommandLogToConsole($oRequest))
	->addCommand(new cliCommandHelp($oRequest))
	->addCommand(new testCommandListTestCases($oRequest))
	// test all|package subpackage
	->addCommand(
		new testCommand(
			$oRequest, new cliCommandChain(
				array(
					new cliCommandNull($oRequest, 'all', 'Run all test cases', false, false),
					new cliCommandNull(
						$oRequest, 'package',
						'Run test case(s) for specific package. Requires <packagename> and '.
						'optionally <testcase>."\n".e.g. test package <packagename> <testcase>',
						true, false, false
					)
				)
			)
		)
	);
$oApp->getListeners()->attachListener(new cliApplicationListenerLog());
$oApp->execute($oRequest);